apps/AcountApp/urls.py
from django.urls import path
from . import views
app_name="AcountApp"
urlpatterns=[

    path("login/",views.LoginView.as_view(),name="login"),
    path("register/",views.RegisterView.as_view(),name="register"),
    path("logout/",views.LogOutView.as_view(),name="LogOut"),
    path("forget-pass/",views.ForgetPassView.as_view(),name="forgetPass"),
    path("check-otc-forget-pass/",views.PassForgetOtp.as_view(),name="check-otc-forget-pass"),
    path("chnage-pass/",views.ChangePassView.as_view(),name="change-pass"),
    path("pass-change-complate/",views.PassChangeComplateView.as_view(),name="complate-pass-cjange"),
    path("user-detail/<int:pk>/",views.UserDetailView.as_view(),name="UserDetail"),
    path("otp/",views.OtpView.as_view(),name="OTP")
]

apps/HomeApp/urls.py
from django.urls import path
from . import views

app_name="HomeApp"
urlpatterns=[
    path("",views.HomeAppView.as_view(),name="HomeApp"),
    path("search/",views.SearchView.as_view(),name="serach"),
    path("mojavez/",views.MojavezView.as_view(),name="mojavez"),

]

configs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("apps.HomeApp.urls")),
                  path("acount/", include("apps.AcountApp.urls")),
                  path("news/", include("apps.NewsApp.urls")),
                  path("unions/", include("apps.GuildRoomApp.urls")),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path("userpanel/", include("apps.UserPanelApp.urls")),
                  path("events/", include("apps.EventsApp.urls")),
                  path("contact-us/",include("apps.contactByMeapp.urls")),
                  path("cart/",include("apps.PaymentsApps.urls")),
                  path("rules/",include("apps.RulesApp.urls")),
                  path("about-us/",include("apps.AboutUsApp.urls")),
                  path("supervision/",include("apps.supervisionApp.urls")),
                  path("charsoo/",include("apps.CharsooApp.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/AcountApp/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django_jalali.db import models as jmodels
from ckeditor.fields import RichTextField
from django.utils import timezone
POST_CHOICES = (
    ("رئیس", "رئیس"),
    ("نائب رئیس اول", "نائب رئیس اول"),
    ("نائب رئیس دوم", "نائب رئیس دوم"),
    ("مدیراجرایی", "مدیر اجرایی"),
    ("خزانه دار", "خزانه دار"),
    ("کاربر عادی", "کاربر عادی"),
    ("عضو", "عضو"),
)
class UserManager(BaseUserManager):
    def create_user(self,phone, password=None):

        if not phone:
            raise ValueError("Users must have an phone Number")

        user = self.model(
            phone=phone,

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,phone,password=None):

        user = self.create_user(
            phone=phone,
            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    phone=models.CharField(max_length=12,
                           verbose_name="شماره تلفن",
                           unique=True)

    fullname=models.CharField(max_length=50,null=True,blank=True,verbose_name="نام و نام خانوادگی")
    email = models.EmailField(
        verbose_name="آدرس ایمیل",
        max_length=255,
        unique=True,
        null=True,
        blank=True
    )


    image=models.FileField(upload_to="users/images",null=True,blank=True,
                           verbose_name="عکس")
    is_publishing_news=models.BooleanField(default=False,verbose_name="اجازه ارسال اخبار دارد؟")
    guild_member=models.BooleanField(default=False,verbose_name="عضو اتحادیه")
    is_supervision=models.BooleanField(default=False,verbose_name="عضو نظارت و بازرسی")
    post = models.CharField(choices=POST_CHOICES,
                            null=True, blank=True,
                            max_length=50,
                            default="کاربر عادی",
                            verbose_name="سمت-مقام")
    is_active = models.BooleanField(default=True,verbose_name="کاربر فعال است؟")
    is_admin = models.BooleanField(default=False,verbose_name="ادمین وبسایت(به همه چیز دسترسی دارد)")
    commissions_member=models.BooleanField(default=False,
                                           verbose_name="عضو کمیسیون می باشد؟")
    board_of_directors=models.BooleanField(default=False,
                                           verbose_name="عضو هیئت رئیسه می باشد؟")
    created=models.DateTimeField(auto_now_add=True)
    bio=RichTextField(null=True,blank=True,
                      verbose_name="بیوگرافی")

    def __str__(self):

        return f"{self.fullname}"

    objects = UserManager()

    USERNAME_FIELD = "phone"


    class Meta:
        verbose_name="کاربر"
        verbose_name_plural="کاربرها"


    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True



    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin,self.is_publishing_news


class OtpClass(models.Model):
    phone=models.CharField(max_length=14)
    fullname=models.CharField(max_length=50,null=True)
    password=models.CharField(max_length=60,blank=True)
    code=models.CharField(max_length=15)
    expiration_date=models.DateTimeField()

    def is_expiration_date(self):

        if self.expiration_date >= timezone.now():

            return True
        else:
            return False

    def __str__(self):

        return f"{self.phone}-{self.code}"


class PasswordResetTokenOtp(models.Model):
    phone=models.CharField(max_length=15)
    token=models.CharField(max_length=50)
    expiration_date = models.DateTimeField()


    def is_expiration_date(self):

        if self.expiration_date >= timezone.now():

            return True
        else:
            return False

apps/AcountApp/views.py
from django.utils import timezone
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,View
from apps.AcountApp.models import User,OtpClass,PasswordResetTokenOtp
from django.contrib.auth import login,logout,authenticate
import random
import requests
import ghasedakpack
from .mixin import CheckLoginMixinMixin
sms = ghasedakpack.Ghasedak("091fd79dad29615b1b1ca22a91beac3c83db83baba36b25e28ef054650d7d71e")


class LoginView(CheckLoginMixinMixin,View):

    def get(self,request):

        return render(request,"AcountApp/login.html")

    def post(self,request):
        phone=request.POST.get("phone")
        password=request.POST.get("pass")

        if phone and password:
            if User.objects.filter(phone=phone).exists():
                user=authenticate(phone=phone,password=password)
                if user is not None:
                    login(request,user)

                    return redirect("/")
                else:
                    return render(request, "AcountApp/login.html",
                                  {"error": "کاربری با این مشخصات در سایت وجود ندارد"})
            else:
                return render(request,"AcountApp/login.html",
                              {"error":"کاربری با این مشخصات در سایت وجود ندارد"})

        return render(request,"AcountApp/login.html")

class RegisterView(CheckLoginMixinMixin,View):

    def get(self,request):


        return render(request,"AcountApp/register.html")

    def post(self,request):

        fullname=request.POST.get("fullname")
        phone=request.POST.get("phone")
        pass1=request.POST.get("password1")
        pass2=request.POST.get("password2")

        if fullname and phone and pass2 and pass1:

            if User.objects.filter(phone=phone).exists():

                return render(request,"AcountApp/register.html",{"error":"حساب کاربری با این شماره در سایت وجود دارد!"})

            else:

                if pass2 != pass1:

                    return render(request,"AcountApp/register.html",{"error":"پسوردها با هم شباهت ندارند!"})
                else:
                    code=random.randint(1000,9999)
                    OtpClass.objects.create(phone=phone,code=code,
                                            fullname=fullname,password=pass2,expiration_date=timezone.now()+timezone.timedelta(minutes=5))

                    request.session["code"]=code
                    request.session["phone"]=phone

                    sms.verification(
                        {'receptor': phone,
                         'type': '1', 'template': 'registersms',
                         'param1':code})

                    return redirect("AcountApp:OTP")

        return render(request,"AcountApp/register.html")


class LogOutView(View):
    def get(self,request):

        if request.user.is_authenticated:

            logout(request)
            return redirect('/')

class ForgetPassView(CheckLoginMixinMixin,View):

    def post(self,request):
        phone=request.POST.get("phone")


        if User.objects.filter(phone=phone).exists():

            code=random.randint(1000,9999)
            OtpClass.objects.create(phone=phone,code=code,expiration_date=timezone.now()+timezone.timedelta(minutes=5))

            request.session["phone_forget"]=phone
            request.session["code_forget"]=code

            sms.verification(
                {'receptor': phone,
                 'type': '1', 'template': 'registersms',
                 'param1': code})

            return redirect("AcountApp:check-otc-forget-pass")

        return render(request,"AcountApp/forgetpass.html")

    def get(self,request):

        return render(request,"AcountApp/forgetpass.html")


class PassForgetOtp(CheckLoginMixinMixin,View):

    def get(self,request):
        phone = request.session.get("phone_forget")

        return render(request,"AcountApp/otpforgetpass.html",{"phone":phone})

    def post(self,request):
        context={
            "error":[]
        }
        phone = request.session.get("phone_forget")
        code = request.session.get("code_forget")



        c_1 = request.POST.get("c_1")
        c_2 = request.POST.get("c_2")
        c_3 = request.POST.get("c_3")
        c_4 = request.POST.get("c_4")

        if c_1 and c_2 and c_3 and c_4:
            otpcode = c_1 + c_2 + c_3 + c_4

            if OtpClass.objects.filter(phone=phone, code=code).exists():
                otp = OtpClass.objects.get(phone=phone, code=code)

                if otp.code == otpcode:

                    if otp.is_expiration_date():
                        code=random.randint(1000,9999)
                        OtpClass.objects.create(phone=otp.phone,code=code)
                        request.session["chnage_pass_code"]=code
                        request.session["chnage_pass_phone"]=otp.phone
                        otp.delete()

                        del request.session['phone_forget']
                        del request.session['code_forget']

                        return redirect("AcountApp:change-pass")


                    else:
                        otp.delete()
                        del request.session['phone_forget']
                        del request.session['code_forget']
                        context["error"].append("کد وارد شده فاقد اعتبار است")
                        return render(request, "AcountApp/otpforgetpass.html", context)
                else:
                    otp.delete()
                    context["error"].append("کد وارد شده فاقد اعتبار است")
                    del request.session['phone_forget']
                    del request.session['code_forget']
                    return render(request, "AcountApp/otpforgetpass.html", context)

            else:
                del request.session['phone_forget']
                del request.session['code_forget']
                context["error"].append("کد وارد شده اشتباه است")
                return render(request, "AcountApp/otpforgetpass.html",context)

        return render(request, "AcountApp/otpforgetpass.html")


class ChangePassView(CheckLoginMixinMixin,View):
    def get(self,request):

        return render(request,"AcountApp/changePass.html")

    def post(self,request):
        pass1=request.POST.get("pass1")
        pass2=request.POST.get("pass2")

        if pass1 == pass2:
            code=request.session.get("chnage_pass_code")
            phone=request.session.get("chnage_pass_phone")

            del request.session['chnage_pass_code']
            del request.session['chnage_pass_phone']

            if OtpClass.objects.filter(phone=phone,code=code).exists():
                otc=OtpClass.objects.get(phone=phone,code=code)
                user=User.objects.get(phone=otc.phone)
                user.set_password(pass2)
                user.save()
                otc.delete()

                return redirect("AcountApp:complate-pass-cjange")


        else:
            pass

        return render(request,"AcountApp/changePass.html")


class PassChangeComplateView(CheckLoginMixinMixin,TemplateView):
    template_name = "AcountApp/complate_pass_change.html"

class OtpView(CheckLoginMixinMixin,View):

    def get(self,request):
        phone = request.session.get("phone")


        return render(request,"AcountApp/otp.html",{"phone":phone})

    def post(self,request):
        context={
            "error":[]
        }

        phone = request.session.get("phone")
        code = str(request.session.get("code"))

        del request.session['phone']
        del request.session['code']

        c_1=request.POST.get("c_1")
        c_2=request.POST.get("c_2")
        c_3=request.POST.get("c_3")
        c_4=request.POST.get("c_4")

        if c_1 and c_2 and c_3 and c_4:
            otpcode=c_1+c_2+c_3+c_4


            if OtpClass.objects.filter(phone=phone, code=code).exists():

                otp = OtpClass.objects.get(phone=phone)

                #check otp experition_date
                if otp.is_expiration_date():
                    if code == otpcode:

                        user=User.objects.create(fullname=otp.fullname,
                                                phone=otp.phone,
                                                password=otp.password)

                        user.set_password(otp.password)
                        user.save()
                        otp.delete()
                        login(request,user)
                        return redirect("/")

                    else:
                        otp.delete()
                        context["error"].append("کد وارد شده صحیح نمی باشد!")

                        return render(request, "AcountApp/otp.html", context)
                else:
                    otp.delete()
                    context["error"].append("کد وارد شده منقضی شده است!")
                    return render(request, "AcountApp/otp.html",context)
            else:
                context["error"].append("کد وارد شده صحیح نمی باشد!")

                return render(request, "AcountApp/otp.html",context)

class UserDetailView(View):

    def get(self,request,pk):
        user=User.objects.get(id=pk)

        return render(request,"AcountApp/userdetail.html",{"user":user})

apps/AcountApp/templates/AcountApp/changePass.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تغییر رمز عبور</title>
    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">


    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">


    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>
<body>

{% include "include/header.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg">
            <section class="page-account-box">
                <div class="col-lg-6 col-md-6 col-xs-12 mx-auto">
                    <div class="ds-userlogin">
                        <a href="{% url "HomeApp:HomeApp" %}" class="account-box-logo">اتاق اصناف سیرجان</a>
                        <div class="account-box">

                            <div class="Login-to-account mt-4">
                                <div class="account-box-content">
                                    {% if error %}

                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>

                                    {% endif %}
                                    <h4>بازیابی رمز عبور</h4>
                                    <form method="post" class="form-account text-right">
                                        {% csrf_token %}
                                        <div class="form-account-title">
                                            <label for="email-phone">رمز خود را وارد کنید</label>
                                            <input type="password" class="number-email-input" placeholder="رمز خود را وارد کنید" id="email-phone" name="pass1">
                                        </div>

                                        <div class="form-account-title">
                                            <label for="email-phone">رمز خود را وارد کنید</label>
                                            <input type="password" class="number-email-input" placeholder="رمز خود را وارد کنید" id="email-phone" name="pass2">
                                        </div>


                                        <div class="form-row-account">
                                            <button class="btn btn-primary btn-login">بازیابی رمز</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

{% include "include/footer.html" %}


<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>
<!-- login----------------------------------->

<!-- scroll_Progress------------------------->
<div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
</div>
<!-- scroll_Progress------------------------->

</body>
<!-- file js---------------------------------------------------->
<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>
<!-- plugin----------------------------------------------------->
<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>
<!-- main js---------------------------------------------------->
<script src="{% static "assets/js/main.js" %}"></script>
</html>

apps/AcountApp/templates/AcountApp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ورود</title>
    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">


    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">


    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>
<body>

{% include "include/header.html" %}


<div class="container">
    <div class="row">
        <div class="col-lg">
            <section class="page-account-box">
                <div class="col-lg-6 col-md-6 col-xs-12 mx-auto">
                    <div class="ds-userlogin">
                        <a href="#" class="account-box-logo">digismart</a>
                        <div class="account-box">
                            <div class="account-box-headline">
                                <a href="{% url "AcountApp:login" %}" class="login-ds active">
                                    <span class="title">ورود</span>
                                    <span class="sub-title">به اتاق اصناف سیرجان</span>
                                </a>
                                <a href="{% url "AcountApp:register" %}" class="register-ds">
                                    <span class="title">ثبت نام</span>
                                    <span class="sub-title">در اتاق اصناف سیرجان</span>
                                </a>
                            </div>
                            <div class="Login-to-account mt-4">
                                <div class="account-box-content">
                                    {% if error %}

                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>

                                    {% endif %}
                                    <h4>ورود</h4>
                                    <form method="post" class="form-account text-right">
                                        {% csrf_token %}
                                        <div class="form-account-title">
                                            <label for="email-phone">شماره موبایل</label>
                                            <input type="text" class="number-email-input" id="email-phone" name="phone">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="password">رمز عبور</label>
                                            <a href="{% url "AcountApp:forgetPass" %}" class="account-link-password">رمز خود را فراموش کرده ام</a>
                                            <input type="password" class="password-input" name="pass">
                                        </div>

                                        <div class="form-row-account">
                                            <button class="btn btn-primary btn-login">ورود به اتاق اصناف سیرجان</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>


{% include "include/footer.html" %}

<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>


<!-- login----------------------------------->

<!-- scroll_Progress------------------------->
<div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
</div>
<!-- scroll_Progress------------------------->

</body>
<!-- file js---------------------------------------------------->

<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>
<!-- plugin----------------------------------------------------->
<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>

<!-- main js---------------------------------------------------->
<script src="{% static "assets/js/main.js" %}"></script>
</html>

apps/AcountApp/templates/AcountApp/register.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ثبت نام</title>
    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">


    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">


    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>
<body>

<!-- login----------------------------------->

{% include "include/header.html" %}



<div class="container">
    <div class="row">
        <div class="col-lg">
            <section class="page-account-box">
                <div class="col-lg-6 col-md-6 col-xs-12 mx-auto">
                    <div class="ds-userlogin">
                        <a href="#" class="account-box-logo"></a>
                        <div class="account-box">
                            <div class="account-box-headline">

                                <a href="{% url "AcountApp:login" %}" class="login-ds">
                                    <span class="title">ورود</span>
                                    <span class="sub-title">به اتاق اصناف سیرجان</span>


                                <a href="{% url "AcountApp:register" %}" class="register-ds active">
                                    <span class="title">ثبت نام</span>
                                    <span class="sub-title">در اتاق اصناف سیرجان</span>
                                </a>
                            </div>
                            <div class="Login-to-account mt-4">
                                <div class="account-box-content">
                                    {% if error %}

                                    <div class="alert alert-danger" role="alert">
                                        {{ error }}
                                    </div>

                                    {% endif %}
                                    <h4>ثبت نام</h4>
                                    <form  class="form-account text-right" method="post">
                                        {% csrf_token %}
                                        <div class="form-account-title">
                                            <label for="email-phone">نام و نام خانوادگی</label>
                                            <input type="text" class="number-email-input" id="email-phone" name="fullname">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="email-phone">شماره موبایل</label>
                                            <input type="text" class="number-email-input" id="email-phone" name="phone">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="password">رمز عبور</label>
                                            <input type="password" class="password-input" name="password1">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="password">تکرار رمز عبور</label>
                                            <input type="password" class="password-input" name="password2">
                                        </div>

                                        <div class="form-row-account">
                                            <button class="btn btn-primary btn-login">ثبت نام در اتاق اصناف سیرجان</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!-- login----------------------------------->


{% include "include/footer.html" %}


<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>

<!-- scroll_Progress------------------------->
<div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
</div>
<!-- scroll_Progress------------------------->

</body>
<!-- file js---------------------------------------------------->
<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>
<!-- plugin----------------------------------------------------->
<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>
<!-- main js---------------------------------------------------->
<script src="{% static "assets/js/main.js" %}"></script>
</html>