apps/HomeApp/urls.py
from django.urls import path
from . import views

app_name="HomeApp"
urlpatterns=[
    path("",views.HomeAppView.as_view(),name="HomeApp"),
    path("search/",views.SearchView.as_view(),name="serach"),
    path("mojavez/",views.MojavezView.as_view(),name="mojavez"),

]

apps/supervisionApp/urls.py
from django.urls import path
from . import views


app_name="supervisionApp"
urlpatterns=[
    path("list/",views.AllSupervision.as_view(),name="All-Supervision"),
    path("detail/<int:pk>/",views.DetailSupervision.as_view(),name="detail-Supervision")
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("apps.HomeApp.urls")),
                  path("acount/", include("apps.AcountApp.urls")),
                  path("news/", include("apps.NewsApp.urls")),
                  path("unions/", include("apps.GuildRoomApp.urls")),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path("userpanel/", include("apps.UserPanelApp.urls")),
                  path("events/", include("apps.EventsApp.urls")),
                  path("contact-us/",include("apps.contactByMeapp.urls")),
                  path("cart/",include("apps.PaymentsApps.urls")),
                  path("rules/",include("apps.RulesApp.urls")),
                  path("about-us/",include("apps.AboutUsApp.urls")),
                  path("supervision/",include("apps.supervisionApp.urls")),
                  path("charsoo/",include("apps.CharsooApp.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/supervisionApp/models.py
from django.db import models
from apps.AcountApp.models import User
from django.utils.text import slugify
from django.shortcuts import reverse

class Supervision(models.Model):
    name = models.CharField(max_length=50, verbose_name="نظارت و بازرسی")
    user = models.ManyToManyField(User, limit_choices_to={"is_supervision": True},
                                  related_name="Supervision"
                                  , verbose_name="افراد")
    slug = models.SlugField(allow_unicode=True, null=True, blank=True)

    def save(self, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)

        super().save(**kwargs)

    def get_absolut_url(self):
        return reverse("supervisionApp:detail-Supervision", args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "نظارت و بازرسی"
        verbose_name_plural = "نظارت و بازرسی"

apps/supervisionApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from .models import Supervision


class AllSupervision(ListView):
    model =Supervision
    template_name = "supervisionApp/all-supervisionApp.html"


class DetailSupervision(DetailView):
    model = Supervision
    template_name = "supervisionApp/supervision-detail.html"

apps/supervisionApp/templates/supervisionApp/all-supervisionApp.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

  <section class="container py-5">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "HomeApp:HomeApp" %}">خانه</a></li>
                        <li class="breadcrumb-item"><a href="{% url "supervisionApp:All-Supervision" %}">نظارت و بازرسی</a></li>
                    </ol>
                </nav>

            <h3 class="my-4 text-center title-section">  نظارت و بازرسی ها </h3>

            <div class="row">

                        {% for item in object_list %}
                        <!-- item -->
                        <div class="col-lg-3 col-md-6 my-2">
                            <div class="teachers-item custom-bg p-2 ">
                                <div class="d-flex align-items-center pb-5 border-bottom">
                                    <div class="px-2 position-relative w-100  ">
                                        <p class="font-weight-bold text-center">کمیسیون {{ item.name }}</p>
                                        <p class="teacher-email position-absolute pt-2 text-center" style="width: inherit;">

                                                تعداد اعضا:{{ item.user.all.count }}

                                        </p>
                                    </div>
                                </div>

                                <div class=" d-flex align-items-center justify-content-center p-2">
                                    <a href="{{ item.get_absolut_url }}" class="btn w-75 custom-btn">
                                        مشاهده کمیسیون</a>
                                </div>
                            </div>
                        </div>
                        <!-- end item -->
                {% endfor %}


            </div>
        </section>





    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}

apps/supervisionApp/templates/supervisionApp/supervision-detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

    <div class="container">


        <div class="row">
            <section class="my-5 container bg-white py-5">
            <h3 class="our-team-title">اعضای بازرسی و نظارت {{ object.name }}</h3>
            <div class="d-flex align-items-center justify-content-center flex-wrap">
                <!-- item -->
                    {% for item in object.user.all %}
                    <div class="member">
                        <div class="member-img-box">

                                {% if item.image %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{{ item.image.url }}">
                            {% else %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{% static "img/user.png" %}">
                            {% endif %}

                            <div class="member-overlay"></div>
                        </div>
                        <p>{{ item.fullname }}-{{ item.post }}</p>
                        <p>شماره تلفن:{{ item.phone }}</p>
                    </div>
                {% endfor %}



            </div>
        </section>
        </div>
    </div>

    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}