apps/HomeApp/urls.py
from django.urls import path
from . import views

app_name="HomeApp"
urlpatterns=[
    path("",views.HomeAppView.as_view(),name="HomeApp"),
    path("search/",views.SearchView.as_view(),name="serach"),
    path("mojavez/",views.MojavezView.as_view(),name="mojavez"),

]

apps/PaymentsApps/urls.py
from django.urls import path
from . import views

app_name="PaymentsApp"
urlpatterns=[

  path("",views.CartView.as_view(),name="Cart"),
  path("add/<int:pk>",views.AddToCartView.as_view(),name="add-cart"),
  path("add-cart-to-order/",views.AddCartTOOrder.as_view(),name="add-cart-to-order"),
  path("del-item-from-order/<int:pk>",views.DelFromCartView.as_view(),name="del-item-from-order"),
  path("pay/<int:pk>",views.PayZarinPallView.as_view(),name="PayZarinPallView"),
  path("del-from-order/<int:pk>",views.DelFromOrder.as_view(),name="del-from-order"),
  path("paycart/<int:pk>",views.SendToZarinpallView.as_view(),name="send-to-zarin"),
  path("verify/",views.VerifyView.as_view(),name="verify")
  ]

apps/UserPanelApp/urls.py
from django.urls import path
from . import views

app_name="UserPanelApp"
urlpatterns=[
    path("",views.UserPanelView.as_view(),name="userpanel"),
    path("edit-profile/",views.EditProfile.as_view(),name="edit-panel"),
    path("profile-order/",views.OrderProfileView.as_view(),name="order-profile"),
    path("order/<int:pk>",views.OrderProfileDetail.as_view(),name="order-detail"),
    path("pass-change/",views.ChangePasswordView.as_view(),name="pass-change")
]

configs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("apps.HomeApp.urls")),
                  path("acount/", include("apps.AcountApp.urls")),
                  path("news/", include("apps.NewsApp.urls")),
                  path("unions/", include("apps.GuildRoomApp.urls")),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path("userpanel/", include("apps.UserPanelApp.urls")),
                  path("events/", include("apps.EventsApp.urls")),
                  path("contact-us/",include("apps.contactByMeapp.urls")),
                  path("cart/",include("apps.PaymentsApps.urls")),
                  path("rules/",include("apps.RulesApp.urls")),
                  path("about-us/",include("apps.AboutUsApp.urls")),
                  path("supervision/",include("apps.supervisionApp.urls")),
                  path("charsoo/",include("apps.CharsooApp.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/UserPanelApp/forms.py
from django import forms
from apps.AcountApp.models import User

class EditProfileForm(forms.ModelForm):

    class Meta:
        model=User

        fields=("fullname","image","bio")

        widgets={
            "fullname":forms.TextInput(
                attrs={
                    "class":"input-namefirst-checkout form-control"
                }
            ),
            "image":forms.FileInput(attrs={
                "class":"input-namefirst-checkout form-control"
            }),
            "bio":forms.Textarea(attrs={
                "class":"input-namefirst-checkout form-control summernote"
            })
        }

apps/UserPanelApp/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,View
from .forms import EditProfileForm
from django.urls import reverse
from apps.PaymentsApps.models import OrderShop
from apps.AcountApp.models import User
from django.contrib.auth import login
from .mixin import CheckLoginRequiredMixin

class UserPanelView(CheckLoginRequiredMixin,TemplateView):

    template_name = "UserPanelApp/profile.html"

class EditProfile(CheckLoginRequiredMixin,View):


    def post(self,request):

        form=EditProfileForm(request.POST,request.FILES,instance=request.user)

        if form.is_valid():
            form.save()

        return redirect(reverse("UserPanelApp:edit-panel"))


    def get(self,request):
        form=EditProfileForm(instance=request.user)

        return render(request,"UserPanelApp/edit-profile.html",{"form":form})



class OrderProfileView(CheckLoginRequiredMixin,View):

    def get(self,request):
        order=OrderShop.objects.filter(user=request.user)

        return render(request,"UserPanelApp/profile-order.html",{"order":order})

class OrderProfileDetail(CheckLoginRequiredMixin,View):

    def get(self,request,pk):
        order=OrderShop.objects.get(id=pk)

        return render(request,"UserPanelApp/order_detail.html",{"order":order})


class ChangePasswordView(CheckLoginRequiredMixin,View):

    def get(self,request):


        return render(request,"UserPanelApp/password-chanage.html")


    def post(self,request):

        oldpass=request.POST.get("oldpass")
        pass1=request.POST.get("pass1")
        pass2=request.POST.get("pass2")
        user=User.objects.get(phone=request.user.phone)
        context={
            "error":[]
        }

        if pass1 and pass2 and oldpass:

           if user.check_password(oldpass):

               if pass1 == pass2:

                   user.set_password(pass1)
                   user.save()
                   login(request, user)

                   return redirect("UserPanelApp:userpanel")

               else:
                   context["error"].append("پسورد ها با هم شباهت ندارند")
                   return render(request, "UserPanelApp/password-chanage.html",context)

           else:
               context["error"].append("پسورد قدیمی اشتباه است")
               return render(request, "UserPanelApp/password-chanage.html",context)

        return render(request,"UserPanelApp/password-chanage.html")

apps/UserPanelApp/templates/UserPanelApp/order_detail.html
{% load static %}
{% load jformat %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">


    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/materialdesignicons.css" %}">
    <!-- plugin-------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/noUISlider.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/nice-select.css" %}">
    <!-- main-style---------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/responsive.css" %}">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>اتاق اصناف سیرجان</title>

    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>

<body>

{% include "include/header.html" %}


<div class="container-main">
        <div class="d-block">
            <section class="profile-home">
                <div class="col-lg">
                    <div class="post-item-profile order-1 d-block">
                        {% include "include/post-item.html" %}
                        <div class="col-lg-9 col-md-9 col-xs-12 pl">
                            <div class="profile-content">
                                <div class="profile-stats">
                                    <div class="table-orders">

                                        <table class="table table-profile-orders">
                                            <thead class="thead-light">
                                                <tr>

                                                    <th scope="col">عنوان</th>
                                                    <th scope="col">زمان برگذاری</th>
                                                    <th scope="col">قیمت</th>
                                                    <th scope="col">دسته بندی</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in order.event.all %}
                                                <tr>

                                                    <td>{{ item.title }}</td>
                                                    {% if item.is_can_register %}
                                                    <td class="Waiting text-success">{{ item.the_date_of_the_event | timeuntil }} دیگر </td>
                                                        {% else %}
                                                        <td class="Waiting text-danger">برگزار شده</td>
                                                        {% endif %}
                                                    <td class="totla">
                                                        <span class="amount">{{ item.get_price }}
                                                            <span>تومان</span>
                                                        </span>
                                                    </td>
                                                <td class="order-code">{{ item.categoryevent }}</td>
 
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>


{% include "include/footer.html" %}


<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>


<script src="{% static "js/jquery.2.1.0.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/popper.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/owl.carousel.js" %}"></script>
<script src="{% static "js/js.js" %}" type="text/javascript"></script>


</body>
<!-- file js---------------------------------------------------->
<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>
<!-- plugin----------------------------------------------------->
<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.nice-select.min.js" %}"></script>
<!-- main js---------------------------------------------------->
<script src="{% static "assets/js/main.js" %}"></script>
<script>


    $('.dropdown-toggle').dropdown()
</script>

apps/UserPanelApp/templates/UserPanelApp/password-chanage.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تغییر رمز عبور</title>
    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">


    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">


    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>
<body>

{% include "include/header.html" %}

<div class="container">
    <div class="row">
        <div class="col-lg">
            <section class="page-account-box">
                <div class="col-lg-6 col-md-6 col-xs-12 mx-auto">
                    <div class="ds-userlogin">
                        <a href="{% url "HomeApp:HomeApp" %}" class="account-box-logo">اتاق اصناف سیرجان</a>
                        <div class="account-box">
                            <div class="Login-to-account mt-4">
                                {% if error %}
                                    {% for item in error %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ item }}
                                    </div>
                                    {% endfor %}
                                {% endif %}
                                <div class="account-box-content">
                                    <h4 class="mb-2">تغییر رمز عبور</h4>
                                    <form method="post" class="form-account text-right">
                                        {% csrf_token %}
                                        <div class="form-account-title">
                                            <label for="password">رمز عبور قبلی</label>
                                            <input type="password" class="password-input" name="oldpass">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="password">رمز عبور جدید</label>
                                            <input type="password" class="password-input" name="pass1">
                                        </div>
                                        <div class="form-account-title">
                                            <label for="password">تکرار رمز عبور جدید</label>
                                            <input type="password" class="password-input" name="pass2">
                                        </div>
                                        <div class="form-row-account">
                                            <button class="btn btn-primary btn-login">تغییر رمز عبور</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<!-- login----------------------------------->

{% include "include/footer.html" %}

<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>
<!-- login----------------------------------->

<!-- scroll_Progress------------------------->
<div class="progress-wrap">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"/>
    </svg>
</div>
<!-- scroll_Progress------------------------->

</body>
<!-- file js---------------------------------------------------->
<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>
<!-- plugin----------------------------------------------------->
<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>
<!-- main js---------------------------------------------------->
<script src="{% static "assets/js/main.js" %}"></script>
<script>


    $('.dropdown-toggle').dropdown()
</script>
</html>

apps/UserPanelApp/templates/UserPanelApp/profile-order.html
{% load static %}
{% load jformat %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <meta charset="UTF-8">


    <!-- font---------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/materialdesignicons.css" %}">
    <!-- plugin-------------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/vendor/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/noUISlider.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/vendor/nice-select.css" %}">
    <!-- main-style---------------------------------->
    <link rel="stylesheet" href="{% static "assets/css/main.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/responsive.css" %}">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>اتاق اصناف سیرجان</title>

    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
    <link href="{% static "css/style001.css" %}" type="text/css" rel="stylesheet">

    <link href="{% static "css/hircana.css" %}" type="text/css" rel="stylesheet">
</head>

<body>

{% include "include/header.html" %}


<div class="container-main">
        <div class="d-block">
            <section class="profile-home">
                <div class="col-lg">
                    <div class="post-item-profile order-1 d-block">
                        {% include "include/post-item.html" %}
                        <div class="col-lg-9 col-md-9 col-xs-12 pl">
                            <div class="profile-content">
                                <div class="profile-stats">
                                    <div class="table-orders">

                                        <table class="table table-profile-orders">
                                            <thead class="thead-light">
                                                <tr>

                                                    <th scope="col">تاریخ ثبت سفارش</th>
                                                    <th scope="col">وضعیت</th>
                                                    <th scope="col">مجموع</th>
                                                    <th scope="col">جزئیات</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in order %}
                                                <tr>

                                                    <td>{{ item.create |jformat:"%Y/%m/%d" }}</td>
                                                    {% if item.is_pay %}
                                                    <td class="Waiting text-success">پرداخت شده</td>
                                                        {% else %}
                                                        <td class="Waiting text-danger">پرداخت نشده</td>
                                                    {% endif %}
                                                    <td class="totla">
                                                        <span class="amount">{{ item.get_price }}
                                                            <span>تومان</span>
                                                        </span>
                                                    </td>
                                                <td class="order-code"><a href="{% url "UserPanelApp:order-detail" item.id %}">مشاهده</a></td>
                                                {% if item.is_pay == False %}
                                                <td class="order-code"><a href="{% url "PaymentsApp:send-to-zarin" item.id %}">پرداخت</a></td>
                                                {% endif %}
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>


{% include "include/footer.html" %}



<div class="scrolltop" onclick="scroll_top()">
    <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
</div>


<script src="{% static "js/jquery.2.1.0.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/popper.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/owl.carousel.js" %}"></script>
<script src="{% static "js/js.js" %}" type="text/javascript"></script>


</body>

<script src="{% static "assets/js/vendor/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "assets/js/vendor/bootstrap.js" %}"></script>

<script src="{% static "assets/js/vendor/owl.carousel.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.countdown.js" %}"></script>
<script src="{% static "assets/js/vendor/ResizeSensor.min.js" %}"></script>
<script src="{% static "assets/js/vendor/theia-sticky-sidebar.min.js" %}"></script>
<script src="{% static "assets/js/vendor/wNumb.js" %}"></script>
<script src="{% static "assets/js/vendor/nouislider.min.js" %}"></script>
<script src="{% static "assets/js/vendor/jquery.nice-select.min.js" %}"></script>

<script src="{% static "assets/js/main.js" %}"></script>
<script>


    $('.dropdown-toggle').dropdown()
</script>