apps/AcountApp/urls.py
from django.urls import path
from . import views
app_name="AcountApp"
urlpatterns=[

    path("login/",views.LoginView.as_view(),name="login"),
    path("register/",views.RegisterView.as_view(),name="register"),
    path("logout/",views.LogOutView.as_view(),name="LogOut"),
    path("forget-pass/",views.ForgetPassView.as_view(),name="forgetPass"),
    path("check-otc-forget-pass/",views.PassForgetOtp.as_view(),name="check-otc-forget-pass"),
    path("chnage-pass/",views.ChangePassView.as_view(),name="change-pass"),
    path("pass-change-complate/",views.PassChangeComplateView.as_view(),name="complate-pass-cjange"),
    path("user-detail/<int:pk>/",views.UserDetailView.as_view(),name="UserDetail"),
    path("otp/",views.OtpView.as_view(),name="OTP")
]

apps/GuildRoomApp/urls.py
from django.urls import path
from . import views

app_name="GuildRoomApp"
urlpatterns=[
        path("list/",views.UnionListView.as_view(),name="List"),
        path("detail/<int:pk>",views.UnionDetailVew.as_view(),name="DetailGuild"),
        path("member-of-guildroom",
             views.MemberOfUnionList.as_view()
             ,name="MemberOfUnionList"),
        path("comision-list/",views.ComisionListView.as_view(),name="Comision-list"),
        path("comision-detail/<int:pk>/",views.ComisionDetailView.as_view(),name="comision-detail")
]

apps/HomeApp/urls.py
from django.urls import path
from . import views

app_name="HomeApp"
urlpatterns=[
    path("",views.HomeAppView.as_view(),name="HomeApp"),
    path("search/",views.SearchView.as_view(),name="serach"),
    path("mojavez/",views.MojavezView.as_view(),name="mojavez"),

]

configs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path("", include("apps.HomeApp.urls")),
                  path("acount/", include("apps.AcountApp.urls")),
                  path("news/", include("apps.NewsApp.urls")),
                  path("unions/", include("apps.GuildRoomApp.urls")),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path("userpanel/", include("apps.UserPanelApp.urls")),
                  path("events/", include("apps.EventsApp.urls")),
                  path("contact-us/",include("apps.contactByMeapp.urls")),
                  path("cart/",include("apps.PaymentsApps.urls")),
                  path("rules/",include("apps.RulesApp.urls")),
                  path("about-us/",include("apps.AboutUsApp.urls")),
                  path("supervision/",include("apps.supervisionApp.urls")),
                  path("charsoo/",include("apps.CharsooApp.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/GuildRoomApp/models.py
from django.db import models
from apps.AcountApp.models import User
from django.utils.text import slugify
from django.urls import reverse

class GuildRoomModel(models.Model):
    name=models.CharField(max_length=50,verbose_name="نام اتحادیه")
    user=models.ManyToManyField(User,limit_choices_to={"guild_member":True},
    related_name="User"
    ,verbose_name="افراد")
    slug=models.SlugField(allow_unicode=True,null=True,blank=True)


    def save(self,**kwargs):
        self.slug=slugify(self.name,allow_unicode=True)

        super().save(**kwargs)

    def get_absolut_url(self):

        return reverse("GuildRoomApp:DetailGuild",args=[self.id])

    def __str__(self):


        return self.name

    class Meta:

        verbose_name="اتحادیه"
        verbose_name_plural="اتحادیه ها"


class CommissionsModel(models.Model):
    name=models.CharField(max_length=50,verbose_name="نام کمیسون")
    user=models.ManyToManyField(User,limit_choices_to={"commissions_member":True},
    related_name="Comision"
    ,verbose_name="افراد")
    slug=models.SlugField(allow_unicode=True,null=True,blank=True)


    def save(self,**kwargs):
        self.slug=slugify(self.name,allow_unicode=True)

        super().save(**kwargs)

    def get_absolut_url(self):

        return reverse("GuildRoomApp:comision-detail",args=[self.id])

    def __str__(self):


        return self.name

    class Meta:

        verbose_name="کمیسیون"
        verbose_name_plural="کمیسیون ها"

apps/GuildRoomApp/forms.py
from django import forms
from . models import GuildRoomModel

class NormalUserPostForm(forms.ModelForm):
    class Meta:
        model = GuildRoomModel
        fields =("name",)

class AdminUserPostForm(forms.ModelForm):
    class Meta:
        model = GuildRoomModel
        fields = "__all__"

apps/GuildRoomApp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from .models import GuildRoomModel,CommissionsModel
from apps.AcountApp.models import User

class UnionListView(ListView):

    template_name = "GuildRoomApp/List_of_unions.html"
    model = GuildRoomModel

class UnionDetailVew(DetailView):
    model = GuildRoomModel
    template_name = "GuildRoomApp/show_union.html"


class MemberOfUnionList(ListView):
    model = User
    template_name = "GuildRoomApp/listOfmemberUnion.html"

    def get_queryset(self):
        qs = super().get_queryset()

        return qs.filter(board_of_directors=True)


class ComisionListView(ListView):
    template_name = "GuildRoomApp/list_of_comision.html"
    model = CommissionsModel

    # def get_queryset(self):
    #     qs=super(ComisionListView, self).get_queryset()
    #
    #     return qs.filter(commissions_member=True)

class ComisionDetailView(DetailView):
    model = CommissionsModel
    template_name = "GuildRoomApp/comision_detail.html"

apps/GuildRoomApp/templates/GuildRoomApp/List_of_unions.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

  <section class="container py-5">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "HomeApp:HomeApp" %}">خانه</a></li>
                        <li class="breadcrumb-item"><a href="{% url "GuildRoomApp:List" %}"> اتحادیه ها</a></li>
                    </ol>
                </nav>

            <h3 class="my-4 text-center title-section"> اتحادیه ها </h3>

            <div class="row">

                        {% for item in object_list %}
                        <!-- item -->
                        <div class="col-lg-3 col-md-6 my-2">
                            <div class="teachers-item custom-bg p-2 ">
                                <div class="d-flex align-items-center pb-5 border-bottom">
                                    <div class="px-2 position-relative w-100  ">
                                        <p class="font-weight-bold text-center">اتحادیه {{ item.name }}</p>
                                        <p class="teacher-email position-absolute pt-2 text-center" style="width: inherit;">

                                                تعداد اعضا:{{ item.user.all.count }}

                                        </p>
                                    </div>
                                </div>

                                <div class=" d-flex align-items-center justify-content-center p-2">
                                    <a href="{{ item.get_absolut_url }}" class="btn w-75 custom-btn">
                                        مشاهده اتحادیه</a>
                                </div>
                            </div>
                        </div>
                        <!-- end item -->
                {% endfor %}








            </div>
        </section>








    <!--end content-->



    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}

apps/GuildRoomApp/templates/GuildRoomApp/comision_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

    <div class="container">


        <div class="row">
            <section class="my-5 container bg-white py-5">
            <h3 class="our-team-title">اعضای کمیسیون {{ object.name }}</h3>
            <div class="d-flex align-items-center justify-content-center flex-wrap">
                <!-- item -->
                    {% for item in object.user.all %}
                    <div class="member">
                        <div class="member-img-box">

                                {% if item.image %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{{ item.image.url }}">
                            {% else %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{% static "img/user.png" %}">
                            {% endif %}

                            <div class="member-overlay"></div>
                        </div>
                        <p>{{ item.fullname }}-{{ item.post }}</p>
                        <p>شماره تلفن:{{ item.phone }}</p>
                    </div>
                {% endfor %}



            </div>
        </section>
        </div>
    </div>

    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}

apps/GuildRoomApp/templates/GuildRoomApp/listOfmemberUnion.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

    <div class="container">


        <div class="row">
            <section class="my-5 container bg-white py-5">
            <h3 class="our-team-title">هیئت رئیسه اتاق اصناف سیرجان</h3>
            <div class="d-flex align-items-center justify-content-center flex-wrap">
                <!-- item -->
                    {% for item in object_list %}
                    <div class="member">
                        <div  class="member-img-box">

                                {% if item.image %}
                                    <a href="{% url "AcountApp:UserDetail" item.id %}">
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{{ item.image.url }}">
                                    </a>
                            {% else %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{% static "img/user.png" %}">
                            {% endif %}

                            <div class="member-overlay"></div>
                        </div>

                    <a href="{% url "AcountApp:UserDetail" item.id %}" class="text text-dark">
                        <p>{{ item.fullname }}-{{ item.post }}</p>
                    </a>

                    </div>
                {% endfor %}



            </div>
        </section>
        </div>
    </div>

    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}

apps/GuildRoomApp/templates/GuildRoomApp/list_of_comision.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

  <section class="container py-5">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "HomeApp:HomeApp" %}">خانه</a></li>
                        <li class="breadcrumb-item"><a href="{% url "GuildRoomApp:List" %}"> کمیسیون ها</a></li>
                    </ol>
                </nav>

            <h3 class="my-4 text-center title-section"> کمیسیون ها </h3>

            <div class="row">

                        {% for item in object_list %}
                        <!-- item -->
                        <div class="col-lg-3 col-md-6 my-2">
                            <div class="teachers-item custom-bg p-2 ">
                                <div class="d-flex align-items-center pb-5 border-bottom">
                                    <div class="px-2 position-relative w-100  ">
                                        <p class="font-weight-bold text-center">کمیسیون {{ item.name }}</p>
                                        <p class="teacher-email position-absolute pt-2 text-center" style="width: inherit;">

                                                تعداد اعضا:{{ item.user.all.count }}

                                        </p>
                                    </div>
                                </div>

                                <div class=" d-flex align-items-center justify-content-center p-2">
                                    <a href="{{ item.get_absolut_url }}" class="btn w-75 custom-btn">
                                        مشاهده کمیسیون</a>
                                </div>
                            </div>
                        </div>
                        <!-- end item -->
                {% endfor %}


            </div>
        </section>





    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}

apps/GuildRoomApp/templates/GuildRoomApp/show_union.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <!--begin content-->
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet">

    <div class="container">

        <div class="row">
            <section class="my-5 container bg-white py-5">
            <h3 class="our-team-title">اعضای اتحادیه {{ object.name }}</h3>
            <div class="d-flex align-items-center justify-content-center flex-wrap">
                <!-- item -->
                    {% for item in object.user.all %}
                    <div class="member">
                        <div class="member-img-box">

                                {% if item.image %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{{ item.image.url }}">
                            {% else %}
                                    <img alt="{{ item.fullname }}" class="ui circular image"
                                     src="{% static "img/user.png" %}">
                            {% endif %}

                            <div class="member-overlay"></div>
                        </div>
                        <p>{{ item.fullname }}-{{ item.post }}</p>
                        <p>شماره تماس:{{ item.phone }}</p>
                    </div>
                {% endfor %}



            </div>
        </section>
        </div>
    </div>

    <div class="scrolltop" onclick="scroll_top()">
        <i class="fa fa-chevron-up arrow_icon" style="color: #333"></i>
    </div>


{% endblock %}